// Generated by CoffeeScript 1.5.0
(function() {

  describe('Sharkbone.ViewManager', function() {
    var subject;
    subject = Sharkbone.ViewManager;
    it('should be defined', function() {
      return expect(subject).toBeDefined();
    });
    describe('Navigation helpers', function() {
      return it('should include its methods', function() {
        expect(subject.prototype.goToIndex).toBeDefined();
        return expect(subject.prototype.goToShow).toBeDefined();
      });
    });
    return describe('Route helpers', function() {
      return it('should include its methods', function() {
        expect(subject.prototype.getRootPath).toBeDefined();
        expect(subject.prototype.getResourceId).toBeDefined();
        expect(subject.prototype.indexPath).toBeDefined();
        expect(subject.prototype.showPath).toBeDefined();
        return expect(subject.prototype.editPath).toBeDefined();
      });
    });
  });

}).call(this);
