// Generated by CoffeeScript 1.5.0
(function() {

  describe('Initializers', function() {
    var subject;
    subject = Sharkbone.App.Initializers;
    return it('should be defined', function() {
      return expect(subject).toBeDefined();
    });
  });

}).call(this);
