// Generated by CoffeeScript 1.5.0
(function() {

  describe('Object extensions', function() {
    var subject;
    subject = Object;
    return it('should be able to define methods', function() {
      return expect(subject.define).toBeDefined();
    });
  });

}).call(this);
