// Generated by CoffeeScript 1.5.0
(function() {

  describe('Object extensions', function() {
    var subject;
    subject = Object;
    return it('should be able to addMethod', function() {
      return expect(subject.addMethod).toBeDefined();
    });
  });

}).call(this);
