// Generated by CoffeeScript 1.5.0
(function() {

  describe('String', function() {
    var subject;
    subject = null;
    beforeEach(function() {
      return subject = String;
    });
    it('should be able to define methods', function() {
      return expect(subject.define).toBeDefined();
    });
    return describe('isBlank', function() {
      beforeEach(function() {
        return subject = subject.prototype.isBlank;
      });
      it('should be defined', function() {
        return expect(subject).toBeDefined();
      });
      it('should return true for empty string', function() {
        return expect(''.isBlank()).toBeTruthy();
      });
      it('should return true for a string with whitespaces', function() {
        return expect('     '.isBlank()).toBeTruthy();
      });
      it('should return false for "dummy" string', function() {
        return expect('dummy'.isBlank()).toBeFalsy();
      });
      return it('should return false for "  d u m m y  " string', function() {
        return expect('  d u m m y  '.isBlank()).toBeFalsy();
      });
    });
  });

}).call(this);
