// Generated by CoffeeScript 1.5.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  describe('Sharkbone.Router', function() {
    var subject;
    subject = Sharkbone.Router;
    it('should be defined', function() {
      return expect(subject).toBeDefined();
    });
    describe('defaultCollectionName', function() {
      it('should be a function', function() {
        return expect(subject.defaultCollectionName).toEqual(jasmine.any(Function));
      });
      return it('should return empty string if no Router extends the subject', function() {
        return expect(subject.defaultCollectionName()).toEqual('');
      });
    });
    return describe('being extended by FirstAwesomesRouter', function() {
      var local_subject;
      local_subject = {};
      beforeEach(function() {
        Sharkbone.App.Routers.FirstAwesomesRouter = (function(_super) {

          __extends(FirstAwesomesRouter, _super);

          function FirstAwesomesRouter() {
            FirstAwesomesRouter.__super__.constructor.apply(this, arguments);
          }

          return FirstAwesomesRouter;

        })(subject);
        local_subject = Sharkbone.App.Routers.FirstAwesomesRouter;
        spyOn(local_subject, 'defaultCollectionName').andCallThrough();
        spyOn(local_subject, 'collectionClass').andCallThrough();
        spyOn(local_subject, 'collectionName').andCallThrough();
        spyOn(local_subject, 'resources').andCallThrough();
        return local_subject.resources();
      });
      it('should be defined', function() {
        return expect(Sharkbone.App.Routers.FirstAwesomesRouter).toEqual(jasmine.any(Function));
      });
      describe('defaultCollectionName', function() {
        it('should have been called', function() {
          return expect(local_subject.defaultCollectionName).toHaveBeenCalled();
        });
        return it('should return FirstAwesomesRouter', function() {
          return expect(local_subject.defaultCollectionName()).toEqual('FirstAwesomes');
        });
      });
      describe('collectionClass', function() {
        it('should have been called', function() {
          return expect(local_subject.collectionClass).toHaveBeenCalled();
        });
        return it('should return FirstAwesomes', function() {
          return expect(local_subject.collectionClass()).toEqual('FirstAwesomes');
        });
      });
      describe('collectionName', function() {
        it('should have been called', function() {
          return expect(local_subject.collectionName).toHaveBeenCalled();
        });
        return it('should return FirstAwesomes', function() {
          return expect(local_subject.collectionName()).toEqual('first_awesomes');
        });
      });
      describe('resources', function() {
        it('should have been called', function() {
          return expect(local_subject.resources).toHaveBeenCalled();
        });
        return it('routes attribute should equal expected object', function() {
          return expect(local_subject.prototype.routes).toEqual({
            'first_awesomes/index': 'index',
            'first_awesomes': 'index',
            'first_awesomes/new': 'newModel',
            'first_awesomes/:id/edit': 'edit',
            'first_awesomes/:id': 'show'
          });
        });
      });
      return describe('initialize', function() {
        beforeEach(function() {
          Sharkbone.App.Collections.FirstAwesomes = jasmine.createSpy('FirstAwesomes').andReturn({
            model: 'FirstAwesome'
          });
          Sharkbone.App.Routers.FirstAwesomes = (function(_super) {

            __extends(FirstAwesomes, _super);

            function FirstAwesomes() {
              FirstAwesomes.__super__.constructor.apply(this, arguments);
            }

            return FirstAwesomes;

          })(Sharkbone.Router);
          spyOn(Sharkbone.App.Routers.FirstAwesomes.prototype, 'initialize').andCallThrough();
          return local_subject = new Sharkbone.App.Routers.FirstAwesomes();
        });
        it('should have been called', function() {
          return expect(local_subject.initialize).toHaveBeenCalled();
        });
        return it('should create a collection of FirstAwesomes', function() {
          return expect(local_subject.collection).toEqual({
            model: 'FirstAwesome'
          });
        });
      });
    });
  });

}).call(this);
