// Generated by CoffeeScript 1.3.3
(function() {

  describe('App', function() {
    var subject;
    subject = Sharkbone.App;
    it('should be defined', function() {
      return expect(subject).toBeDefined();
    });
    describe('activeRouters', function() {
      return it('should be an empty array', function() {
        return expect(subject.activeRouters).toEqual([]);
      });
    });
    describe('options', function() {
      it('should be an object', function() {
        return expect(subject.options).toEqual(jasmine.any(Object));
      });
      return it('should have a pushState attribute with a falsy value', function() {
        return expect(subject.options.pushState).toBeFalsy();
      });
    });
    return describe('initialize method', function() {
      it('should be a defined', function() {
        return expect(subject.initialize).toBeDefined();
      });
      return it('should be a function', function() {
        return expect(subject.initialize).toEqual(jasmine.any(Function));
      });
    });
  });

}).call(this);
