// Generated by CoffeeScript 1.5.0
(function() {

  describe('Sharkbone namespace', function() {
    return it('should be defined', function() {
      return expect(Sharkbone).toEqual(jasmine.any(Object));
    });
  });

}).call(this);
