// Generated by CoffeeScript 1.5.0
(function() {

  describe('Sharkbone.Modules.Render', function() {
    var subject;
    subject = null;
    beforeEach(function() {
      var template;
      subject = Sharkbone.Modules.Render;
      return template = jasmine.createSpy('template').andCallFake(function() {
        return '<div>data</div>';
      });
    });
    it('should be defined', function() {
      return expect(subject).toBeDefined();
    });
    describe('render', function() {
      return it('should be defined', function() {
        return expect(subject.render).toBeDefined();
      });
    });
    describe('renderData', function() {
      return it('should be defined', function() {
        return expect(subject.renderData).toBeDefined();
      });
    });
    describe('renderResource', function() {
      return it('should be defined', function() {
        return expect(subject.renderResource).toBeDefined();
      });
    });
    describe('renderCollection', function() {
      return it('should be defined', function() {
        return expect(subject.renderCollection).toBeDefined();
      });
    });
    return describe('renderPagination', function() {
      return it('should be defined', function() {
        return expect(subject.renderPagination).toBeDefined();
      });
    });
  });

}).call(this);
