// Generated by CoffeeScript 1.5.0
(function() {

  describe('Sharkbone.Model', function() {
    var subject;
    subject = Sharkbone.Model;
    it('should be defined', function() {
      return expect(subject).toBeDefined();
    });
    it('should have the extend method', function() {
      return expect(subject.extend).toEqual(jasmine.any(Function));
    });
    it('should have the include method', function() {
      return expect(subject.include).toEqual(jasmine.any(Function));
    });
    return it('should have the appNamespace method', function() {
      return expect(subject.appNamespace).toEqual(jasmine.any(Function));
    });
  });

}).call(this);
