// Generated by CoffeeScript 1.5.0
(function() {

  describe('Sharkbone.Model', function() {
    return it('should be defined', function() {
      return expect(Sharkbone.Model).toBeDefined();
    });
  });

}).call(this);
