// Generated by CoffeeScript 1.5.0
(function() {

  describe('Sharkbone namespace', function() {
    it('should be defined', function() {
      return expect(Sharkbone).toBeDefined();
    });
    describe('Version', function() {
      return it('should be defined', function() {
        return expect(Sharkbone.Version).toBeDefined();
      });
    });
    describe('Config namespace', function() {
      return it('should be defined', function() {
        return expect(Sharkbone.Config).toBeDefined();
      });
    });
    describe('Modules namespace', function() {
      return it('should be defined', function() {
        return expect(Sharkbone.Modules).toBeDefined();
      });
    });
    describe('ClassModules namespace', function() {
      return it('should be defined', function() {
        return expect(Sharkbone.ClassModules).toBeDefined();
      });
    });
    return describe('App namespace', function() {
      it('should be defined', function() {
        return expect(Sharkbone.App).toBeDefined();
      });
      describe('Models namespace', function() {
        return it('should be defined', function() {
          return expect(Sharkbone.App.Models).toBeDefined();
        });
      });
      describe('Collections namespace', function() {
        return it('should be defined', function() {
          return expect(Sharkbone.App.Collections).toBeDefined();
        });
      });
      describe('Views namespace', function() {
        return it('should be defined', function() {
          return expect(Sharkbone.App.Views).toBeDefined();
        });
      });
      describe('Routers namespace', function() {
        return it('should be defined', function() {
          return expect(Sharkbone.App.Routers).toBeDefined();
        });
      });
      return describe('Initializers', function() {
        it('should be defined', function() {
          return expect(Sharkbone.App.Initializers).toBeDefined();
        });
        it('should have an initializeRouters method', function() {
          return expect(Sharkbone.App.Initializers.initializeRouters).toEqual(jasmine.any(Function));
        });
        return it('should have a setupBackboneRelational method', function() {
          return expect(Sharkbone.App.Initializers.setupBackboneRelational).toEqual(jasmine.any(Function));
        });
      });
    });
  });

}).call(this);
